BI_LSTM_TEST_SIZE = 0.1
BI_LSTM_TRAIN_SIZE = 0.8
BI_LSTM_VAL_SIZE = 0.1

BI_LSTM_BUFFER_SIZE = 10000
BI_LSTM_BATCH_SIZE = 32
BI_LSTM_EPOCH = 10
BI_LSTM_OPTIMIZER_NAME = 'adam'  # sgd, adam, adamax, adadelta, adagrad = 10
BI_LSTM_DROPOUT_RATE = 0.1
BI_LSTM_LEARNING_RATE = 3e-5
BI_LSTM_SAVE_MODEL_NAME = 'res7_bert'
BI_LSTM_SAVE_MODEL_DIR = './saved_models'