import tensorflow

PREPROCESS_SEQ_LEN = 128
PREPROCESS_BATCH_SIZE = 32
PREPROCESS_BUFFER_SIZE = tensorflow.data.AUTOTUNE

PREPROCESS_DO_SHUFFLING = False

PREPROCESS_IGNORE_EXC_STR = True

PREPROCESS_ONLY_SOURCE_TWEET = False

BERT_TEST_SIZE = 0.2
BERT_TRAIN_SIZE = 0.6
BERT_VAL_SIZE = 0.2


BERT_EPOCHS = 15
BERT_BATCH_SIZE = 32
BERT_DROPOUT_RATE = 0.1
BERT_LEARNING_RATE = 3e-5
BERT_OPTIMIZER_NAME = 'adam'  # sgd, adam, adamax, adadelta, adagrad
BERT_SAVE_MODEL_NAME = 'res8_bert'
BERT_SAVE_MODEL_DIR = './saved_models'
